# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GO8j33RYL3SAt67To09y7LtY4RmAqZ23
"""

print("--- Atividade 1 ---")
resposta = input("Deseja continuar no sistema? (Sim/Não): ")


if resposta.lower() == "sim":
    print("Continuando...")
else:
    print("Encerrando...")

print("\n" + "="*40 + "\n")


print("--- Atividade 2 ---")
uf = input("Digite a sigla do seu estado (ex: sp, rj, mg): ")


uf_padronizada = uf.upper()
print(f"Estado cadastrado: {uf_padronizada}")

print("\n" + "="*40 + "\n")


print("--- Atividade 3 ---")
CUPOM_VALIDO = "DESCONTO10"
cupom_usuario = input("Digite o seu cupom promocional: ")


if cupom_usuario.upper() == CUPOM_VALIDO:
    print("Cupom aplicado com sucesso!")
else:
    print("Cupom inválido.")

print("\n" + "="*40 + "\n")


print("--- Atividade 4 ---")
nome = input("Digite o seu primeiro nome: ")


nome_limpo = nome.strip()
print(f"Nome limpo: {nome_limpo}")
print(f"Quantidade exata de caracteres: {len(nome_limpo)}")

print("\n" + "="*40 + "\n")


print("--- Atividade 5 ---")
email = input("Digite o seu e-mail: ")


if email.strip() == "":
    print("Erro: O campo e-mail não pode ficar em branco!")
else:
    print("E-mail cadastrado!")

print("\n" + "="*40 + "\n")


print("--- Atividade 6 ---")
USUARIO_CORRETO = "aluno@escola.com"
login_usuario = input("Digite seu login (e-mail): ")


login_tratado = login_usuario.strip().lower()

if login_tratado == USUARIO_CORRETO:
    print("Login realizado com sucesso!")
else:
    print("Falha no login: Usuário incorreto.")